### ISSUE TITLE
Support for INSERT with SELECT

### ISSUE THREAD

**Issue by kevinoid** [brianc/node-sql#111]
As far as I can tell, node-sql does not currently support `INSERT` statements which insert the result of a query.  Is that correct?  To clarify, I'm thinking about a statement such as the following:

```sql
INSERT INTO interest_charges (account_id, tx_date, amount)
SELECT account_id, NOW(), balance * 0.05
FROM accounts
WHERE balance > 0;
```

There are a number of ways to add support, so I thought it would be prudent to discuss it before jumping in.  Would it make sense to implement it as `table.insert(...).select(...)`?  Should `insert` take an array of columns (or multiple column arguments)?  Any thoughts or interest in implementing it?

**Comment by danrzeppa** [comment]
This functionality was added in pull request #112.
