### ISSUE TITLE
COALESCE support

### ISSUE THREAD

**Issue by billxinli** [brianc/node-sql#219]
Does node-sql support `COALESCE(...)`?

Edit:

Looking at the source: https://github.com/brianc/node-sql/blob/72a9c7a44e6ee031351611a0e638b727833bbefe/lib/functions.js#L38

**Comment by billxinli** [comment]
Is it possible to get a new release out soon?

**Comment by danrzeppa** [comment]
@brianc is going to have to do that. I don't have that capability.

**Comment by brianc** [comment]
Pushed out a new version! sorry to keep you waiting!
