### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by chilion** [brianc/node-sql#236]
I have no clue how to install etc

**Comment by nik045** [comment]
same here

**Comment by devotis** [comment]
`npm install sql`

**Comment by brianc** [comment]
are y'all bein' sneaky & really asking for me to update the readme with
better documentation? I can totes do that if you'd like. ;)

**Comment by devotis** [comment]
Not me :) but the installation part of the readme would take no less than a few minutes of copy pasting generic stuff. Not sure about the etc @chilion is talking about.

**Comment by brianc** [comment]
Updated the readme w/ install instructions...

**Comment by chilion** [comment]
THANK YOU!
