### ISSUE TITLE
Support for date_trunc for PostgreSQL

### ISSUE THREAD

**Issue by davidcl64** [brianc/node-sql#239]
I'd like to generate a where clause that looks something like this:

    WHERE foo.id = $1 AND date_trunc('milliseconds', foo.updated_at) = $2

Is there a way to patch in support for an arbitrary function like this?

If not, is there a way to specify text for the where clause?

Ideally, I'd like to plug this into code that looks something like this:

    return table
      .update(params)
      .where(table.id.equals(params.id), table.updatedAt.equals(params.version))
      .returning(table.star())
      .toQuery();

**Comment by brianc** [comment]
I believe you can generate functions and attach them to your instance.

These tests have a bit more detail: https://github.com/brianc/node-sql/blob/master/test/function-tests.js

Does that give you what you're looking for?

**Comment by davidcl64** [comment]
Yes - thank you.  It took me a bit to grok what to do there but basically I ended up with this:

    SQL.functions.DATE_TRUNC = SQL.functionCallCreator('DATE_TRUNC');

    // usage
    where(SQL.functions.DATE_TRUNC('milliseconds', table.updatedAt).equals(params.version))

Thank you for the pointer!
