### ISSUE TITLE
Where do I specify the connection creds to a database?

### ISSUE THREAD

**Issue by davidann** [brianc/node-sql#244]
In the examples, I see how to execute queries against a database, but I don't see how to specify which database host to execute a query against?

Could you point me to where I would look for these?

**Comment by danrzeppa** [comment]
node-sql doesn't actually execute the query against any particular database. It just generates the SQL statement that can be passed to whichever database you're using.

For example, if you're using the node-postgres library to connect to PostgreSQL, node-sql would integrate like so (I'm mangling the sample code from the node-postgres and node-sql readmes):

```javascript
var sql = require('sql');
var pg = require('pg');

// create schemea for node-sql
var user = sql.define({
  name: 'user',
  columns: ['id', 'name', 'email', 'lastLogin']
});

// connect to a database, and run a query
var conString = "postgres://username:password@localhost/database";
pg.connect(conString, function(err, client, done) {
  if(err) return console.error('error fetching client from pool', err);

   // build a query using node-sql
   var query=user.select().where(user.name.equals("joe")).toQuery()

  // pass the "text" and "values" of the query to the postgresql db
  client.query(query.text, query.values, function(err, result) {
    done();
    if(err) return console.error('error running query', err);
    console.log(result.rows[0].number);
  });
});```

**Comment by davidann** [comment]
@danrzeppa Thanks for the descriptive example.  :smile:
