### ISSUE TITLE
CREATE VIEW support?

### ISSUE THREAD

**Issue by lebolo** [brianc/node-sql#245]
I tried a quick search and didn't find anything. Has there been any discussion about supporting [views](http://www.postgresql.org/docs/9.4/static/sql-createview.html) (particularly for Postgres).

Any thoughts on implementation?

**Comment by edudutra** [comment]
A proposed implementation could be:

```javascript
var query = user.select(user.star()).where(user.name.equals('userName'));

var viewText = query.toView('ViewName');
```

Wich returns 

```SQL
CREATE VIEW "ViewName" AS SELECT "user".* FROM "user" WHERE ("user"."name" = 'userName')
```

I have it already implemented. If this is ok, I can create a PR..

Any thougths?

**Comment by lebolo** [comment]
:+1: seems pretty powerful and flexible to me

**Comment by edudutra** [comment]
Alright. I'll add some test cases and create a PR probably tomorrow.

**Comment by edudutra** [comment]
Hi.

I managed to create the tests and I'm coing to create the PR. I've changed a little bit what I proposed before, changing then ```toView``` to ```createView```. 

So, an example of use would be: 

```javascript
var sql = require('sql');

var user = sql.define({
  name: 'user',
  columns: ['id', 'name']
});

var query = user.select(user.star()).where(user.id.equals(1));

var view = query.createView('myView');

var text = view.toQuery();
```

This returns a query object as folows. Note that since we are creating a view, the parameters are replaced with its values.

```javascript
   {
      text: 'CREATE VIEW "myView" AS SELECT "user".* FROM "user" WHERE ("user"."id" = 1)',
      values: [] 
   }
```

Creating a PR now.
