### ISSUE TITLE
Bug: unique flag not implemented

### ISSUE THREAD

**Issue by pwellner** [brianc/node-sql#266]
``` Javascript
sql.define({
    name: 'foo',
    columns: {
        fooId: { dataType: 'VARCHAR', primaryKey: true },
        bar: { dataType: 'VARCHAR', notNull: true, unique: true }
        }
}).create();
```

Using `pg` this generates
`CREATE TABLE "foo" ("fooId" VARCHAR PRIMARY KEY, "bar" VARCHAR NOT NULL)`
without including the `UNIQUE` constraint.

**Comment by KieronWiltshire** [comment]
I'm also having this issue, I'm just commenting to hope that this issue is bumped.

**Comment by iamcharliegoddard** [comment]
@pwellner and @KieronWiltshire, version 0.65.0 of node-sql should contain a fix for this issue. Could you post back verifying if 0.65.0 fixes the issue?

thanks

**Comment by pwellner** [comment]
Confirmed, thank you.
