### ISSUE TITLE
Should .returning() default to '*' like .select()?

### ISSUE THREAD

**Issue by elmigranto** [brianc/node-sql#272]
`.select()` defaults to selecting everything (`*`), but `.returning()` doesn't. In fact, `returning()` without any arguments will simply append `RETURNING ` to sql query which isn't that useful unless someone is planning to join `.toString()` output somewhere (but you can always pass in expression to `returning` directly).

I think `.returning()` and `.returning('*')` should be the same.

**Comment by brianc** [comment]
I agree with you!  The 'default' generating an invalid query is pretty silly indeed.  Would you be interested in putting together a pull request for this feature? :)

**Comment by elmigranto** [comment]
Okay.
