### ISSUE TITLE
Unique constraint when creating a table.

### ISSUE THREAD

**Issue by nonelove** [brianc/node-sql#283]
Hi team,

I'd like to set unique constraints when creating a table. Could you add a column setting like the following code.

columns: [{
  name: 'email',
  dataType: 'text',
  unique: true,
}]

Thanks.

**Comment by iamcharliegoddard** [comment]
@nonelove, I beleave this might be a duplicate of issue https://github.com/brianc/node-sql/issues/266. Could you install version 0.65.0 of node-sql and verify if 0.65.0 resolves your issue?

thanks

**Comment by nonelove** [comment]
It works well. Thanks!
