### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by tmont** [brianc/node-sql#316]
It looks like this module hasn't been published to NPM in the last 4 months or so, and a lot of stuff has been merged in. Any plan to publish any time soon?

**Comment by brianc** [comment]
Damn! sorry about that! I could have sworn I published recently - I'll push a new minor version right now.

**Comment by brianc** [comment]
published @v0.68.0 - thanks for letting me know!

**Comment by tmont** [comment]
thanks!
