### ISSUE TITLE
Support for Postgres Insert "ON CONFLICT" Clause?

### ISSUE THREAD

**Issue by arikalfus** [brianc/node-sql#333]
Does this library support optional clauses in postgres commands? Specifically, I'm looking at the ON CONFLICT clause on an INSERT ([docs](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT)).

This is new to version 9.5 of Postgres, and basically allows upsert commands without having to resort to a PL/pgSQL function. This SQL example is from the Postgres 9.5 docs linked above:

```
INSERT INTO distributors (did, dname)
    VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc')
    ON CONFLICT (did) DO UPDATE SET dname = EXCLUDED.dname;
```

I didn't see anything similar in the dialect tests, although I may have missed it.

**Comment by rohitishere1** [comment]
the pull request should solve both the referenced issues.

**Comment by rohitishere1** [comment]
Thanks @brianc ! I guess we can close this issue now

**Comment by arikalfus** [comment]
Looks great! PR is merged, so closing this issue.
