### ISSUE TITLE
Multiple conditions on JOIN

### ISSUE THREAD

**Issue by mjesun** [brianc/node-sql#348]
Hi,

I'm trying to add multiple conditions to a JOIN, as seen in http://stackoverflow.com/a/1219924. However, it looks like the result of the `on` call has no `and`, thus you cannot add more constraints to the JOIN.

I could put them as a WHERE later, and this would work, but then the joint table created is bigger than what is actually needed.

**Comment by danrzeppa** [comment]
Put the `and` condition after the equals within the on` function

```
// ucs below is short for user_category_subscriptions
var query=categories.select()
  .from(categories.join(ucs.on(ucs.category_id.equals(categories._id).and(ucs.user_id.equals(1)))))
```

**Comment by mjesun** [comment]
Oooh OK! I think it would be nice to clarify it, I was expecting a similar approach to the `.where`, where the `.and` can also go outside.

Thanks!!
