### ISSUE TITLE
Mysql Support

### ISSUE THREAD

**Issue by gabe-ratcliff** [brianc/node-sql#358]
Hey, I'm loving this library so far, but I've run into a couple snags when attempting to use the mysql dialect. I believe they stem from the same issue.

1) In a `WHERE` clause, when setting to .`equal(${param})`, the query builder returns a `?`. This occurs when passing variables, or hardcoded strings/ints.
2) When working with an `INSERT` builder, passed in variables used as `VALUES` are also returned as `?, ?`. 

It seems that the library isn't interpreting these properly. Any direction would be appreciated!

**Comment by aliem** [comment]
The library doesn't create ready-made queries. It does instead create an object with `text` and `values` properties:

```js
const q = table
    .select(table.star())
    .where(table.id.equals(11));

console.log(q.toQuery());
{
    text: "SELECT * FROM table WHERE id = ?",
    values: [11]
}
```

MySQL node module understands this format and will query the database with the right parameters in the right place. It's more secure than trying to support input sanitization for all supported dialects

**Comment by gabe-ratcliff** [comment]
I see, perfect! Thank you very much.
