### ISSUE TITLE
Other Join types

### ISSUE THREAD

**Issue by Carl-Foster** [brianc/node-sql#373]
It seems like only INNER and LEFT joins are supported. I've been using this library and require FULL OUTER join.

I propose similar to `leftJoin()` just do a `fullOuterJoin()` since it has similar semantics.

**Comment by Carl-Foster** [comment]
I'm happy to do this and submit a PR.

**Comment by Carl-Foster** [comment]
#374 adds these join types

**Comment by iancamp** [comment]
👍 

Looking forward to when this gets merged.
