### ISSUE TITLE
I can't use sql in TypeScript

### ISSUE THREAD

**Issue by AdaVih** [brianc/node-sql#407]
Run in the Angular.
<img width="853" alt="图片" src="https://user-images.githubusercontent.com/35645884/57750861-748e9d00-7716-11e9-8147-9ba44f9ed1fd.png">

**Comment by charsleysa** [comment]
@AdaVih just a heads up it looks like this package isn't maintained anymore https://github.com/brianc/node-sql/issues/405

**Comment by AdaVih** [comment]
It can't find `node-sql-ts` [https://github.com/brianc/node-sql/issues/405](url)
<img width="357" alt="图片" src="https://user-images.githubusercontent.com/35645884/57819430-07811300-77bb-11e9-8ca8-c118dc1176c5.png">

My issue is the same as [https://github.com/brianc/node-sql/issues/406](url)

**Comment by AdaVih** [comment]
@charsleysa

**Comment by charsleysa** [comment]
@AdaVih `node-sql-ts` is a separate repo and package, to install you need to use `npm install sql-ts` and use `import { ... } from 'sql-ts'`

**Comment by AdaVih** [comment]
@charsleysa Thx.I tried the documentation method again, and it worked.
